[package]
name = "arwing_cli"
version = "0.1.0"
edition = "2024"

[dependencies]

arwing_core = { path = "../arwing_core/" }
glob = "0.3.1"
peppi = "2.1.2"
clap = { version = "4.2.0", features = ["cargo"] }
ssbm-data = "0.1.0"
